# Generated by Django 5.1.1 on 2024-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('semi_major_axis', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('inclination', models.FloatField()),
                ('perihelion_distance', models.FloatField()),
                ('aphelion_distance', models.FloatField()),
                ('mean_anomaly_deg', models.FloatField()),
                ('argument_of_periapsis', models.FloatField()),
                ('longitude_of_ascending_node', models.FloatField()),
                ('scaled_distance', models.FloatField()),
                ('is_potentially_hazardous', models.BooleanField(default=False)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('perihelion_distance', models.FloatField()),
                ('semi_major_axis', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('inclination', models.FloatField()),
                ('period_years', models.FloatField()),
                ('time_of_perihelion_passage', models.DateTimeField()),
                ('scaled_distance', models.FloatField()),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('radius_km', models.FloatField()),
                ('orbital_period', models.FloatField()),
                ('semi_major_axis', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('inclination', models.FloatField()),
                ('mean_longitude', models.FloatField()),
                ('longitude_perihelion', models.FloatField()),
                ('longitude_ascending_node', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
